export default {
  'fill': [
    '__arrow__',
    'PhArrowDownFill','PhArrowLeftFill','PhArrowRightFill','PhArrowUpFill','PhArrowFatDownFill','PhArrowFatLeftFill','PhArrowFatRightFill','PhArrowFatUpFill','PhArrowCircleDownFill','PhArrowCircleLeftFill','PhArrowCircleRightFill','PhArrowCircleUpFill','PhCaretDownFill','PhCaretLeftFill','PhCaretRightFill','PhCaretUpFill','PhCaretDoubleDownFill','PhCaretDoubleLeftFill','PhCaretDoubleRightFill','PhCaretDoubleUpFill','PhCaretCircleDownFill','PhCaretCircleLeftFill','PhCaretCircleRightFill','PhCaretCircleUpFill','PhDownloadSimpleFill','PhUploadSimpleFill','PhSignInFill','PhSignOutFill','PhArrowSquareInFill','PhArrowSquareOutFill',

    '__symbols__',
    'PhCircleFill','PhSquareFill','PhTriangleFill','PhClubFill','PhDiamondFill','PhHeartFill','PhHeartStraightFill','PhSpadeFill','PhStarFill','PhStarFourFill','PhStarHalfFill','PhCircleWavyFill','PhHexagonFill','PhOctagonFill','PhRectangleFill','PhWaveSawtooth','PhWaveSine','PhWaveSquare','PhWaveTriangle','PhSpiral','PhCheck','PhPlus','PhMinus','PhX','PhCheckCircleFill','PhCheckSquareFill','PhCircleWavyCheckFill','PhWarningCircleFill','PhWarningFill','PhCircleWavyWarningFill','PhWarningOctagonFill','Ph0questionFill','PhCircleWavyQuestionFill','PhInfoFill','PhPlusCircleFill','PhMinusCircleFill','PhXCircleFill','PhProhibitFill','PhAsterisk','PhDivide','PhEquals','PhMathOperations','PhPercent','PhPlusMinus','PhRadical','PhInfinity','PhNumber1one','PhNumber2two','PhNumber3three','PhNumber4four','PhNumber5five','PhNumber6six','PhNumber7seven','PhNumber8eight','PhNumber9nine','PhNumberZero','PhCopyleft','PhCopyright','PhTrademarkRegistered','PhRecycle',

    '__communication__',
    'PhPhoneFill','PhVoicemail','PhEnvelopeSimpleFill','PhEnvelopeFill','PhChatFill','PhChatDotsFill','PhChatCircleFill','PhChatCircleDotsFill','PhChatsCircleFill','PhChatsFill','PhPaperPlaneRightFill','PhPaperPlaneTiltFill','PhHash','PhShareNetworkFill','PhShareFill','PhBookmarkSimpleFill','PhBookmarkFill','PhBellFill','PhBellRingingFill','PhLightbulbFilamentFill','PhLightbulbFill','PhMegaphoneFill','PhMegaphoneSimpleFill','PhQuotesFill','PhThumbsDownFill','PhThumbsUpFill',

    '__media-file__',
    'PhFileFill','PhFileCodeFill','PhFileTextFill','PhFilesFill','PhCameraFill','PhImageFill','PhImageSquareFill','PhDiscFill','PhMusicNoteFill','PhMusicNotesFill','PhFilmSlateFill','PhFilmStripFill','PhVideoCameraFill','PhMicrophoneFill','PhBroadcastFill','PhEqualizer','PhGif','PhPlaceholderFill','PhApertureFill','PhPrinterFill','PhRadioFill',

    '__works-study__',
    'PhClipboardFill','PhClipboardTextFill','PhCopyFill','Ph1noteFill','PhNoteBlankFill','PhNotePencilFill','PhNotebookFill','PhStickerFill','PhFolderSimpleFill','PhFolderFill','PhFolderOpenFill','PhFolderNotchFill','PhFolderNotchOpenFill','PhFoldersFill','PhArchiveFill','PhTrayFill','PhChartBarFill','PhChartBarHorizontalFill','PhChartLine','PhChartLineUp','PhChartPieFill','PhChartPieSliceFill','PhGraphFill','PhTrendDownFill','PhTrendUpFill','PhPresentationChartFill','PhPresentationFill','PhProjectorScreenChartFill','PhProjectorScreenFill','PhBookBookmarkFill','PhBookFill','PhBookOpenFill','PhBooksFill','PhChalkboardFill','PhGlobeStandFill','PhGraduationCapFill','PhStudentFill','PhAddressBookFill','PhIdentificationBadgeFill','PhIdentificationCardFill','PhBriefcase','PhBriefcaseFill','PhBriefcaseMetalFill','PhSuitcaseFill','PhCalendarBlankFill','PhCalendarFill','Ph1clockFill','PhAlarmFill','PhTimerFill','Ph1hourglassFill','PhHourglassMediumFill','PhCalculatorFill','PhFunnelFill','PhKanbanFill','PhNewspaperFill','PhTableFill','PhAtFill',

    '__shop-money__',
    'PhShoppingCartSimpleFill','PhShoppingCartFill','PhBagFill','PhHandbagFill','PhToteFill','PhTagFill','PhTagSimpleFill','PhBarcode','PhGiftFill','PhPackageFill','PhReceiptFill','PhTicketFill','PhCardholderFill','PhCreditCardFill','PhCoinFill','PhCoinsFill','PhMoneyFill','PhVaultFill','PhWalletFill','PhCurrencyBtc','PhCurrencyCny','PhCurrencyDollarSimple','PhCurrencyDollar','PhCurrencyEthFill','PhCurrencyEur','PhCurrencyGbp','PhCurrencyInr','PhCurrencyJpy','PhCurrencyKrw','PhCurrencyKzt','PhCurrencyNgn','PhCurrencyRub',

    '__living__',
    'PhBeerBottleFill','PhBrandyFill','PhCoffeeFill','PhMartiniFill','PhWineFill','PhCakeFill','PhCookieFill','PhEggFill','PhHamburgerFill','PhPizzaFill','PhPopcornFill','PhForkKnifeFill','PhEyeglassesFill','PhSunglassesFill','PhTShirtFill','PhWatchFill','PhArmchairFill','PhBathtubFill','PhBedFill','PhDoorFill','PhLampFill','PhRugFill','PhShowerFill','PhToiletFill','PhToiletPaperFill','PhBackpackFill','PhBalloonFill','PhBinocularsFill','PhCoatHanger','PhConfettiFill','PhCookingPotFill','PhFlashlightFill','PhHandSoapFill','PhKnifeFill','PhLadderSimple','PhNeedleFill','PhScalesFill',

    '__entertainment__',
    'PhDiceSixFill','PhDiceThreeFill','PhPokerChipFill','PhTargetFill','PhGameControllerFill','PhTelevisionFill','PhTelevisionSimpleFill','PhAlienFill','PhFlyingSaucerFill','PhGhostFill','PhRobotFill','PhSwordFill','PhBaseballFill','PhBasketballFill','PhFootballFill','PhSoccerBallFill','PhTennisBallFill','PhVolleyballFill','PhPianoKeysFill','PhCrownFill','PhCrownSimpleFill','PhMedalFill','PhTrophyFill','PhParachuteFill',

    '__maps-transportation__',
    'Ph1personSimpleWalkFill','PhPersonSimpleRunFill','PhBicycleFill','PhBusFill','PhCarFill','PhJeepFill','PhPoliceCarFill','PhTaxiFill','PhTruckFill','Ph1trainFill','PhTrainSimpleFill','PhAirplaneFill','PhAirplaneInFlightFill','PhAirplaneLandingFill','PhAirplaneTakeoffFill','PhAirplaneTiltFill','PhBoatFill','PhRocketFill','PhRocketLaunchFill','PhHouseFill','PhHouseLineFill','PhBankFill','PhBuildingsFill','PhFactoryFill','PhGasPumpFill','PhStorefrontFill','PhAnchorSimple','PhAnchor','PhBarricadeFill','PhCompassFill','PhCrosshairFill','PhFlagBannerFill','PhFlagFill','PhGaugeFill','PhGlobe','PhHeadlightsFill','PhMapPinFill','PhMapTrifoldFill','PhNavigationArrowFill','PhPathFill','PhPushPinFill','PhSignpostFill','PhTrafficConeFill','PhTrafficSignFill','PhTrafficSignalFill',

    '__system-devices__',
    'PhDesktopFill','PhDesktopTowerFill','PhLaptopFill','PhDeviceTabletCameraFill','PhDeviceTabletSpeakerFill','PhDeviceMobileCameraFill','PhDeviceMobileSpeakerFill','PhHeadphonesFill','PhHeadsetFill','PhMicrophoneStageFill','PhMonitorFill','PhKeyboardFill','PhMouseFill','PhMouseSimpleFill','PhWebcamFill','PhFloppyDiskBackFill','PhFloppyDiskFill','PhSimCardFill','PhComputerTowerFill','PhCpuFill','PhDatabaseFill','PhHardDrivesFill','PhShieldFill','PhShieldCheckFill','PhShieldWarningFill','PhWallFill','PhLockSimpleFill','PhLockSimpleOpenFill','PhFingerprint','PhKeyFill','PhPassword','Ph1magnifyingGlassFill','PhMagnifyingGlassMinusFill','PhMagnifyingGlassPlusFill','PhTrashSimpleFill','PhTrashFill','PhCloudArrowDownFill','PhCloudArrowUpFill','PhDownloadFill','PhUploadFill','PhBatteryEmpty','PhBatteryMediumFill','PhBatteryFullFill','PhBatteryChargingFill','PhBluetooth','PhWifiHigh','PhAppWindowFill','PhBrowserFill','PhBrowsersFill','PhBugDroidFill','PhCodeSimple','PhCode','PhTerminal','PhTerminalWindowFill','PhCursorFill','PhCursorText','PhPlugFill','PhPlugsFill','PhPuzzlePieceFill','PhQrCodeFill','PhSpinnerGap','PhTreeStructureFill','PhFaders','PhSlidersHorizontalFill','Ph1gearFill','PhGearSixFill','PhNutFill','PhWrenchFill',

    '__design__',
    'Ph1pencilSimpleFill','Ph2pencilSimpleLineFill','PhPencilFill','PhPenFill','PhPenNibFill','PhEyedropperFill','PhEyedropperSampleFill','PhPaintBrushFill','PhPaintBrushBroadFill','PhPaintBrushHouseholdFill','PhPaintBucketFill','PhPaintRollerFill','PhPaletteFill','PhSwatchesFill','PhBezierCurveFill','PhCrop','PhEraserFill','PhIntersectFill','PhMagicWandFill','PhMagnetFill','PhPerspectiveFill','PhRulerFill','PhScissors','PhScribbleLoop','PhStampFill','PhCubeFill','PhCylinderFill','Ph2stackSimpleFill','PhStackFill','PhGridFourFill','PhLayoutFill','PhSidebarFill','PhSidebarSimpleFill','PhCirclesFourFill','PhCirclesThreeFill','PhDiamondsFourFill','PhSquaresFourFill',

    '__wellness__',
    'PhBarbellFill','PhHeartBreakFill','PhHeartbeatFill','PhSparkleFill','PhActivity','PhBandaidsFill','PhBrain','PhFaceMaskFill','PhFirstAidFill','PhFirstAidKitFill','PhLifebuoyFill','PhPillFill','PhPrescription','PhSkullFill','PhSyringeFill','PhAtom','PhFlaskFill','PhTestTubeFill',

    '__nature-weather__',
    'PhCampfireFill','PhDropFill','PhFireFill','PhFlameFill','PhLightningFill','PhWaves','PhWind','PhBirdFill','PhBugFill','PhButterflyFill','PhCatFill','PhDogFill','PhFishFill','PhHorseFill','PhPawPrintFill','PhCactusFill','PhFlowerFill','PhFlowerLotusFill','PhLeafFill','PhMountainsFill','PhTreeEvergreenFill','PhTreeFill','PhGlobeHemisphereEastFill','PhGlobeHemisphereWestFill','PhMoonFill','PhPlanetFill','PhCloudFill','PhRainbow','PhSnowflake','PhSunDimFill','PhSunFill','PhUmbrellaSimpleFill','PhUmbrellaFill','PhThermometerSimpleFill','PhThermometerColdFill','PhThermometerHotFill',

    '__people__',
    'PhUserFill','PhUsersFill','PhUsers3threeFill','PhUsersFourFill','Ph1personSimpleFill','PhPersonFill','PhWheelchairFill','PhBabyFill','PhEar','PhEyeClosed','PhEyeFill','PhHandFist','PhHandGrabbing','PhHandPalm','PhHandPointing','PhHandWaving','PhHand','PhHandsClappingFill','PhHandshakeFill','PhSmileyFill','PhSmileyBlankFill','PhSmileyMehFill','PhSmileyNervousFill','PhSmileySadFill','PhSmileyStickerFill','PhSmileyWinkFill','PhSmileyXEyesFill','PhGenderFemale','PhGenderIntersex','PhGenderMale','PhGenderNeuter','PhGenderNonbinary','PhGenderTransgender','PhHandEyeFill','PhPeace','PhYinYangFill',

    '__logo__',
    'PhFacebookLogoFill','PhInstagramLogoFill','PhPinterestLogoFill','PhTiktokLogoFill','PhTwitchLogoFill','PhTwitterLogoFill','PhYoutubeLogoFill','PhLinkedinLogoFill','PhRedditLogoFill','PhSnapchatLogoFill','PhBehanceLogo','PhDribbbleLogoFill','PhMediumLogoFill','PhNyTimesLogo','PhRssSimple','PhRss','PhFigmaLogoFill','PhFramerLogoFill','PhSketchLogoFill','PhCodepenLogo','PhGithubLogoFill','PhDiscordLogoFill','PhSlackLogoFill','PhAppStoreLogo','PhGooglePlayLogoFill','PhApplePodcastsLogoFill','PhGooglePodcastsLogo','PhSpotifyLogoFill',

    '__tools__',
    'PhLinkSimpleHorizontalBreak','PhLinkSimpleHorizontal','PhLinkBreak','PhLinkSimple','PhLink','PhPaperclipHorizontal','PhPaperclip','PhTextBolder','PhTextH','PhTextItalic','PhTextStrikethrough','PhTextT','PhTextUnderline','PhFunction','PhTextAa','PhTextIndentFill','PhTextOutdentFill','PhTextAlignCenter','PhTextAlignJustify','PhTextAlignLeft','PhTextAlignRight','PhListBullets','PhListNumbers','PhFunnelSimple','PhSortAscendingFill','PhSortDescendingFill','PhBackspaceFill','PhKeyReturnFill','PhArrowElbowDownLeftFill','PhCommand','PhOption','PhColumnsFill','PhRowsFill','PhAlignBottomSimpleFill','PhAlignCenterHorizontalSimpleFill','PhAlignCenterVerticalSimpleFill','PhAlignLeftSimpleFill','PhAlignRightSimpleFill','PhAlignTopSimpleFill','PhAlignBottomFill','PhAlignCenterHorizontalFill','PhAlignCenterVerticalFill','PhAlignLeftFill','PhAlignRightFill','PhAlignTopFill','PhGradient','PhCircleHalfFill','PhCircleHalfTiltFill','PhDropHalfBottomFill','PhDropHalfFill','PhSquareHalfBottomFill','PhSquareHalfFill','PhLineSegmentFill','PhLineSegmentsFill','PhPolygonFill','PhBoundingBoxFill','PhSelection','PhGitBranchFill','PhGitCommitFill','PhGitDiffFill','PhGitForkFill','PhGitMergeFill','PhGitPullRequestFill','PhArrowBendUpLeftFill','PhArrowBendUpRightFill','PhArrowUUpLeftFill','PhArrowUUpRightFill','PhArrowClockwiseFill','PhArrowCounterClockwiseFill','PhArrowsClockwiseFill','PhArrowsCounterClockwiseFill','PhArrowsHorizontalFill','PhArrowsVerticalFill','PhArrowsDownUpFill','PhArrowsLeftRightFill','PhArrowLineDownFill','PhArrowLineLeftFill','PhArrowLineRightFill','PhArrowLineUpFill','PhArrowsInLineHorizontalFill','PhArrowsInLineVerticalFill','PhArrowsOutLineHorizontalFill','PhArrowsOutLineVerticalFill','PhArrowsInSimpleFill','PhArrowsOutSimpleFill','PhPauseFill','PhPlayFill','PhRecordFill','PhStopFill','PhRepeatOnce','PhRepeat','PhShuffle','PhFastForwardFill','PhRewindFill','PhSkipBackFill','PhSkipForwardFill','PhSpeakerHighFill','PhSpeakerLowFill','PhSpeakerNoneFill','PhSpeakerSlashFill','PhSpeakerXFill','PhClosedCaptioningFill','PhCornersIn','PhCornersOut','PhFrameCornersFill','PhPictureInPictureFill','PhAirplayFill','PhScreencastFill','PhEjectFill','PhPowerFill','PhDotsThreeVertical','PhDotsThree'],

  'thin': [
    '__arrow__',
    'PhArrowDownThin','PhArrowLeftThin','PhArrowRightThin','PhArrowUpThin','PhArrowFatDownThin','PhArrowFatLeftThin','PhArrowFatRightThin','PhArrowFatUpThin','PhArrowCircleDownThin','PhArrowCircleLeftThin','PhArrowCircleRightThin','PhArrowCircleUpThin','PhCaretDownThin','PhCaretLeftThin','PhCaretRightThin','PhCaretUpThin','PhCaretDoubleDownThin','PhCaretDoubleLeftThin','PhCaretDoubleRightThin','PhCaretDoubleUpThin','PhCaretCircleDownThin','PhCaretCircleLeftThin','PhCaretCircleRightThin','PhCaretCircleUpThin','PhDownloadSimpleThin','PhUploadSimpleThin','PhSignInThin','PhSignOutThin','PhArrowSquareInThin','PhArrowSquareOutThin',

    '__symbols__',
    'PhCircleThin','PhSquareThin','PhTriangleThin','PhClubThin','PhDiamondThin','PhHeartThin','PhHeartStraightThin','PhSpadeThin','PhStarThin','PhStarFourThin','PhStarHalfThin','PhCircleWavyThin','PhHexagonThin','PhOctagonThin','PhRectangleThin','PhWaveSawtoothThin','PhWaveSineThin','PhWaveSquareThin','PhWaveTriangleThin','PhSpiralThin','PhCheckThin','PhPlusThin','PhMinusThin','PhXThin','PhCheckCircleThin','PhCheckSquareThin','PhCircleWavyCheckThin','PhWarningCircleThin','PhWarningThin','PhCircleWavyWarningThin','PhWarningOctagonThin','Ph0questionThin','PhCircleWavyQuestionThin','PhInfoThin','PhPlusCircleThin','PhMinusCircleThin','PhXCircleThin','PhProhibitThin','PhAsteriskThin','PhDivideThin','PhEqualsThin','PhMathOperationsThin','PhPercentThin','PhPlusMinusThin','PhRadicalThin','PhInfinityThin','PhNumber1oneThin','PhNumber2twoThin','PhNumber3threeThin','PhNumber4fourThin','PhNumber5fiveThin','PhNumber6sixThin','PhNumber7sevenThin','PhNumber8eightThin','PhNumber9nineThin','PhNumberZeroThin','PhCopyleftThin','PhCopyrightThin','PhTrademarkRegisteredThin','PhRecycleThin',

    '__communication__',
    'PhPhoneThin','PhVoicemailThin','PhEnvelopeSimpleThin','PhEnvelopeThin','PhChatThin','PhChatDotsThin','PhChatCircleThin','PhChatCircleDotsThin','PhChatsCircleThin','PhChatsThin','PhPaperPlaneRightThin','PhPaperPlaneTiltThin','PhHashThin','PhShareNetworkThin','PhShareThin','PhBookmarkSimpleThin','PhBookmarkThin','PhBellThin','PhBellRingingThin','PhLightbulbFilamentThin','PhLightbulbThin','PhMegaphoneThin','PhMegaphoneSimpleThin','PhQuotesThin','PhThumbsDownThin','PhThumbsUpThin',

    '__media-file__',
    'PhFileThin','PhFileCodeThin','PhFileTextThin','PhFilesThin','PhCameraThin','PhImageSquareThin','PhImageThin','PhDiscThin','PhMusicNoteThin','PhMusicNotesThin','PhFilmSlateThin','PhFilmStripThin','PhVideoCameraThin','PhMicrophoneThin','PhBroadcastThin','PhEqualizerThin','PhGifThin','PhPlaceholderThin','PhApertureThin','PhPrinterThin','PhRadioThin',

    '__works-study__',
    'PhClipboardThin','PhClipboardTextThin','PhCopyThin','Ph1noteThin','PhNoteBlankThin','PhNotePencilThin','PhNotebookThin','PhStickerThin','PhFolderSimpleThin','PhFolderThin','PhFolderOpenThin','PhFolderNotchThin','PhFolderNotchOpenThin','PhFoldersThin','PhArchiveThin','PhTrayThin','PhChartBarThin','PhChartBarHorizontalThin','PhChartLineThin','PhChartLineUpThin','PhChartPieThin','PhChartPieSliceThin','PhGraphThin','PhTrendDownThin','PhTrendUpThin','PhPresentationChartThin','PhPresentationThin','PhProjectorScreenChartThin','PhProjectorScreenThin','PhBookBookmarkThin','PhBookOpenThin','PhBookThin','PhBooksThin','PhChalkboardThin','PhGlobeStandThin','PhGraduationCapThin','PhStudentThin','PhAddressBookThin','PhIdentificationBadgeThin','PhIdentificationCardThin','PhBriefcaseThin','PhBriefcaseMetalThin','PhSuitcaseThin','PhCalendarBlankThin','PhCalendarThin','Ph1clockThin','PhAlarmThin','PhTimerThin','Ph1hourglassThin','PhHourglassMediumThin','PhCalculatorThin','PhFunnelThin','PhKanbanThin','PhNewspaperThin','PhTableThin','PhAtThin',

    '__shop-money__',
    'PhShoppingCartSimpleThin','PhShoppingCartThin','PhBagThin','PhHandbagThin','PhToteThin','PhTagThin','PhTagSimpleThin','PhBarcodeThin','PhGiftThin','PhPackageThin','PhReceiptThin','PhTicketThin','PhCardholderThin','PhCreditCardThin','PhCoinThin','PhCoinsThin','PhMoneyThin','PhVaultThin','PhWalletThin','PhCurrencyBtcThin','PhCurrencyCnyThin','PhCurrencyDollarSimpleThin','PhCurrencyDollarThin','PhCurrencyEthThin','PhCurrencyEurThin','PhCurrencyGbpThin','PhCurrencyInrThin','PhCurrencyJpyThin','PhCurrencyKrwThin','PhCurrencyKztThin','PhCurrencyNgnThin','PhCurrencyRubThin',

    '__living__',
    'PhBeerBottleThin','PhBrandyThin','PhCoffeeThin','PhMartiniThin','PhWineThin','PhCakeThin','PhCookieThin','PhEggThin','PhHamburgerThin','PhPizzaThin','PhPopcornThin','PhForkKnifeThin','PhEyeglassesThin','PhSunglassesThin','PhTShirtThin','PhWatchThin','PhArmchairThin','PhBathtubThin','PhBedThin','PhDoorThin','PhLampThin','PhRugThin','PhShowerThin','PhToiletThin','PhToiletPaperThin','PhBackpackThin','PhBalloonThin','PhBinocularsThin','PhCoatHangerThin','PhConfettiThin','PhCookingPotThin','PhFlashlightThin','PhHandSoapThin','PhKnifeThin','PhLadderSimpleThin','PhNeedleThin','PhScalesThin',

    '__entertainment__',
    'PhDiceSixThin','PhDiceThreeThin','PhPokerChipThin','PhTargetThin','PhGameControllerThin','PhTelevisionThin','PhTelevisionSimpleThin','PhAlienThin','PhFlyingSaucerThin','PhGhostThin','PhRobotThin','PhSwordThin','PhBaseballThin','PhBasketballThin','PhFootballThin','PhSoccerBallThin','PhTennisBallThin','PhVolleyballThin','PhPianoKeysThin','PhCrownThin','PhCrownSimpleThin','PhMedalThin','PhTrophyThin','PhParachuteThin',

    '__maps-transportation__',
    'Ph1personSimpleWalkThin','PhPersonSimpleRunThin','PhBicycleThin','PhBusThin','PhCarThin','PhJeepThin','PhPoliceCarThin','PhTaxiThin','PhTruckThin','Ph1trainThin','PhTrainSimpleThin','PhAirplaneThin','PhAirplaneInFlightThin','PhAirplaneLandingThin','PhAirplaneTakeoffThin','PhAirplaneTiltThin','PhBoatThin','PhRocketThin','PhRocketLaunchThin','PhHouseThin','PhHouseLineThin','PhBankThin','PhBuildingsThin','PhFactoryThin','PhGasPumpThin','PhStorefrontThin','PhAnchorSimpleThin','PhAnchorThin','PhBarricadeThin','PhCompassThin','PhCrosshairThin','PhFlagBannerThin','PhFlagThin','PhGaugeThin','PhGlobeThin','PhHeadlightsThin','PhMapPinThin','PhMapTrifoldThin','PhNavigationArrowThin','PhPathThin','PhPushPinThin','PhSignpostThin','PhTrafficConeThin','PhTrafficSignThin','PhTrafficSignalThin',

    '__system-devices__',
    'PhDesktopThin','PhDesktopTowerThin','PhLaptopThin','PhDeviceTabletCameraThin','PhDeviceTabletSpeakerThin','PhDeviceMobileCameraThin','PhDeviceMobileSpeakerThin','PhHeadphonesThin','PhHeadsetThin','PhMicrophoneStageThin','PhMonitorThin','PhKeyboardThin','PhMouseThin','PhMouseSimpleThin','PhWebcamThin','PhFloppyDiskBackThin','PhFloppyDiskThin','PhSimCardThin','PhComputerTowerThin','PhCpuThin','PhDatabaseThin','PhHardDrivesThin','PhShieldThin','PhShieldCheckThin','PhShieldWarningThin','PhWallThin','PhLockSimpleOpenThin','PhLockSimpleThin','PhFingerprintThin','PhKeyThin','PhPasswordThin','Ph1magnifyingGlassThin','PhMagnifyingGlassMinusThin','PhMagnifyingGlassPlusThin','PhTrashSimpleThin','PhTrashThin','PhCloudArrowDownThin','PhCloudArrowUpThin','PhDownloadThin','PhUploadThin','PhBatteryEmptyThin','PhBatteryMediumThin','PhBatteryFullThin','PhBatteryChargingThin','PhBluetoothThin','PhWifiHighThin','PhAppWindowThin','PhBrowsersThin','PhBugDroidThin','PhCodeSimpleThin','PhCodeThin','PhTerminalThin','PhTerminalWindowThin','PhCursorThin','PhCursorTextThin','PhPlugThin','PhPlugsThin','PhPuzzlePieceThin','PhQrCodeThin','PhSpinnerGapThin','PhTreeStructureThin','PhFadersThin','PhSlidersHorizontalThin','Ph1gearThin','PhGearSixThin','PhNutThin','PhWrenchThin',

    '__design__',
    'Ph1pencilSimpleThin','Ph2pencilSimpleLineThin','PhPencilThin','PhPenThin','PhPenNibThin','PhEyedropperThin','PhEyedropperSampleThin','PhPaintBrushThin','PhPaintBrushBroadThin','PhPaintBrushHouseholdThin','PhPaintBucketThin','PhPaintRollerThin','PhPaletteThin','PhSwatchesThin','PhBezierCurveThin','PhCropThin','PhEraserThin','PhIntersectThin','PhMagicWandThin','PhMagnetThin','PhPerspectiveThin','PhRulerThin','PhScissorsThin','PhScribbleLoopThin','PhStampThin','PhCubeThin','PhCylinderThin','Ph2stackSimpleThin','PhStackThin','PhGridFourThin','PhLayoutThin','PhSidebarThin','PhSidebarSimpleThin','PhCirclesFourThin','PhCirclesThreeThin','PhDiamondsFourThin','PhSquaresFourThin',

    '__wellness__',
    'PhBarbellThin','PhHeartBreakThin','PhHeartbeatThin','PhSparkleThin','PhActivityThin','PhBandaidsThin','PhBrainThin','PhFaceMaskThin','PhFirstAidThin','PhFirstAidKitThin','PhLifebuoyThin','PhPillThin','PhPrescriptionThin','PhSkullThin','PhSyringeThin','PhAtomThin','PhFlaskThin','PhTestTubeThin',

    '__nature-weather__',
    'PhCampfireThin','PhDropThin','PhFireThin','PhFlameThin','PhLightningThin','PhWavesThin','PhWindThin','PhBirdThin','PhBugThin','PhButterflyThin','PhCatThin','PhDogThin','PhFishThin','PhHorseThin','PhPawPrintThin','PhCactusThin','PhFlowerThin','PhFlowerLotusThin','PhLeafThin','PhMountainsThin','PhTreeEvergreenThin','PhTreeThin','PhGlobeHemisphereEastThin','PhGlobeHemisphereWestThin','PhMoonThin','PhPlanetThin','PhCloudThin','PhRainbowThin','PhSnowflakeThin','PhSunDimThin','PhSunThin','PhUmbrellaSimpleThin','PhUmbrellaThin','PhThermometerSimpleThin','PhThermometerColdThin','PhThermometerHotThin',

    '__people__',
    'PhUserThin','PhUsersThin','PhUsers3threeThin','PhUsersFourThin','Ph1personSimpleThin','PhPersonThin','PhWheelchairThin','PhBabyThin','PhEarThin','PhEyeClosedThin','PhEyeThin','PhHandFistThin','PhHandGrabbingThin','PhHandPalmThin','PhHandPointingThin','PhHandThin','PhHandWavingThin','PhHandsClappingThin','PhHandshakeThin','PhSmileyThin','PhSmileyBlankThin','PhSmileyMehThin','PhSmileyNervousThin','PhSmileySadThin','PhSmileyStickerThin','PhSmileyWinkThin','PhSmileyXEyesThin','PhGenderFemaleThin','PhGenderIntersexThin','PhGenderMaleThin','PhGenderNeuterThin','PhGenderNonbinaryThin','PhGenderTransgenderThin','PhHandEyeThin','PhPeaceThin','PhYinYangThin'],

  'regular': [
    '__arrow__',
    'PhArrowDown','PhArrowLeft','PhArrowRight','PhArrowUp','PhArrowFatDown','PhArrowFatLeft','PhArrowFatRight','PhArrowFatUp','PhArrowCircleDown','PhArrowCircleLeft','PhArrowCircleRight','PhArrowCircleUp','PhCaretDown','PhCaretLeft','PhCaretRight','PhCaretUp','PhCaretDoubleDown','PhCaretDoubleLeft','PhCaretDoubleRight','PhCaretDoubleUp','PhCaretCircleDown','PhCaretCircleLeft','PhCaretCircleRight','PhCaretCircleUp','PhDownloadSimple','PhUploadSimple','PhSignIn','PhSignOut','PhArrowSquareIn','PhArrowSquareOut',

    '__symbols__',
    'PhCircle','PhSquare','PhTriangle','PhClub','PhDiamond','PhHeart','PhHeartStraight','PhSpade','PhStar','PhStarFour','PhStarHalf','PhCircleWavy','PhHexagon','PhOctagon','PhRectangle','PhWaveSawtooth','PhWaveSine','PhWaveSquare','PhWaveTriangle','PhSpiral','PhCheck','PhPlus','PhMinus','PhX','PhCheckCircle','PhCheckSquare','PhCircleWavyCheck','PhWarningCircle','PhWarning','PhCircleWavyWarning','PhWarningOctagon','Ph0question','PhCircleWavyQuestion','PhInfo','PhPlusCircle','PhMinusCircle','PhXCircle','PhProhibit','PhAsterisk','PhDivide','PhEquals','PhMathOperations','PhPercent','PhPlusMinus','PhRadical','PhInfinity','PhNumber1one','PhNumber2two','PhNumber3three','PhNumber4four','PhNumber5five','PhNumber6six','PhNumber7seven','PhNumber8eight','PhNumber9nine','PhNumberZero','PhCopyleft','PhCopyright','PhTrademarkRegistered','PhRecycle',

    '__communication__',
    'PhPhone','PhVoicemail','PhEnvelopeSimple','PhEnvelope','PhChat','PhChatDots','PhChatCircle','PhChatCircleDots','PhChatsCircle','PhChats','PhPaperPlaneRight','PhPaperPlaneTilt','PhHash','PhShareNetwork','PhShare','PhBookmarkSimple','PhBookmark','PhBell','PhBellRinging','PhLightbulbFilament','PhLightbulb','PhMegaphone','PhMegaphoneSimple','PhQuotes','PhThumbsDown','PhThumbsUp',

    '__media-file__',
    'PhFile','PhFileCode','PhFileText','PhFiles','PhCamera','PhImageSquare','PhImage','PhDisc','PhMusicNote','PhMusicNotes','PhFilmSlate','PhFilmStrip','PhVideoCamera','PhMicrophone','PhBroadcast','PhEqualizer','PhGif','PhPlaceholder','PhAperture','PhPrinter','PhRadio',

    '__works-study__',
    'PhClipboard','PhClipboardText','PhCopy','Ph1note','PhNoteBlank','PhNotePencil','PhNotebook','PhSticker','PhFolderSimple','PhFolder','PhFolderOpen','PhFolderNotch','PhFolderNotchOpen','PhFolders','PhArchive','PhTray','PhChartBar','PhChartBarHorizontal','PhChartLine','PhChartLineUp','PhChartPie','PhChartPieSlice','PhGraph','PhTrendDown','PhTrendUp','PhPresentationChart','PhPresentation','PhProjectorScreenChart','PhProjectorScreen','PhBookBookmark','PhBookOpen','PhBook','PhBooks','PhChalkboard','PhGlobeStand','PhGraduationCap','PhStudent','PhAddressBook','PhIdentificationBadge','PhIdentificationCard','PhBriefcase','PhBriefcaseMetal','PhSuitcase','PhCalendarBlank','PhCalendar','Ph1clock','PhAlarm','PhTimer','Ph1hourglass','PhHourglassMedium','PhCalculator','PhFunnel','PhKanban','PhNewspaper','PhTable','PhAt',

    '__shop-money__',
    'PhShoppingCartSimple','PhShoppingCart','PhBag','PhHandbag','PhTote','PhTag','PhTagSimple','PhBarcode','PhGift','PhPackage','PhReceipt','PhTicket','PhCardholder','PhCreditCard','PhCoin','PhCoins','PhMoney','PhVault','PhWallet','PhCurrencyBtc','PhCurrencyCny','PhCurrencyDollarSimple','PhCurrencyDollar','PhCurrencyEth','PhCurrencyEur','PhCurrencyGbp','PhCurrencyInr','PhCurrencyJpy','PhCurrencyKrw','PhCurrencyKzt','PhCurrencyNgn','PhCurrencyRub',

    '__living__',
    'PhBeerBottle','PhBrandy','PhCoffee','PhMartini','PhWine','PhCake','PhCookie','PhEgg','PhHamburger','PhPizza','PhPopcorn','PhForkKnife','PhEyeglasses','PhSunglasses','PhTShirt','PhWatch','PhArmchair','PhBathtub','PhBed','PhDoor','PhLamp','PhRug','PhShower','PhToilet','PhToiletPaper','PhBackpack','PhBalloon','PhBinoculars','PhCoatHanger','PhConfetti','PhCookingPot','PhFlashlight','PhHandSoap','PhKnife','PhLadderSimple','PhNeedle','PhScales',

    '__entertainment__',
    'PhDiceSix','PhDiceThree','PhPokerChip','PhTarget','PhGameController','PhTelevision','PhTelevisionSimple','PhAlien','PhFlyingSaucer','PhGhost','PhRobot','PhSword','PhBaseball','PhBasketball','PhFootball','PhSoccerBall','PhTennisBall','PhVolleyball','PhPianoKeys','PhCrown','PhCrownSimple','PhMedal','PhTrophy','PhParachute',

    '__maps-transportation__',
    'Ph1personSimpleWalk','PhPersonSimpleRun','PhBicycle','PhBus','PhCar','PhJeep','PhPoliceCar','PhTaxi','PhTruck','Ph1train','PhTrainSimple','PhAirplane','PhAirplaneInFlight','PhAirplaneLanding','PhAirplaneTakeoff','PhAirplaneTilt','PhBoat','PhRocket','PhRocketLaunch','PhHouse','PhHouseLine','PhBank','PhBuildings','PhFactory','PhGasPump','PhStorefront','PhAnchorSimple','PhAnchor','PhBarricade','PhCompass','PhCrosshair','PhFlagBanner','PhFlag','PhGauge','PhGlobe','PhHeadlights','PhMapPin','PhMapTrifold','PhNavigationArrow','PhPath','PhPushPin','PhSignpost','PhTrafficCone','PhTrafficSign','PhTrafficSignal',

    '__system-devices__',
    'PhDesktop','PhDesktopTower','PhLaptop','PhDeviceTabletCamera','PhDeviceTabletSpeaker','PhDeviceMobileCamera','PhDeviceMobileSpeaker','PhHeadphones','PhHeadset','PhMicrophoneStage','PhMonitor','PhKeyboard','PhMouse','PhMouseSimple','PhWebcam','PhFloppyDiskBack','PhFloppyDisk','PhSimCard','PhComputerTower','PhCpu','PhDatabase','PhHardDrives','PhShield','PhShieldCheck','PhShieldWarning','PhWall','PhLockSimpleOpen','PhLockSimple','PhFingerprint','PhKey','PhPassword','Ph1magnifyingGlass','PhMagnifyingGlassMinus','PhMagnifyingGlassPlus','PhTrashSimple','PhTrash','PhCloudArrowDown','PhCloudArrowUp','PhDownload','PhUpload','PhBatteryEmpty','PhBatteryMedium','PhBatteryFull','PhBatteryCharging','PhBluetooth','PhWifiHigh','PhAppWindow','PhBrowsers','PhBugDroid','PhCodeSimple','PhCode','PhTerminal','PhTerminalWindow','PhCursor','PhCursorText','PhPlug','PhPlugs','PhPuzzlePiece','PhQrCode','PhSpinnerGap','PhTreeStructure','PhFaders','PhSlidersHorizontal','Ph1gear','PhGearSix','PhNut','PhWrench',

    '__design__',
    'Ph1pencilSimple','Ph2pencilSimpleLine','PhPencil','PhPen','PhPenNib','PhEyedropper','PhEyedropperSample','PhPaintBrush','PhPaintBrushBroad','PhPaintBrushHousehold','PhPaintBucket','PhPaintRoller','PhPalette','PhSwatches','PhBezierCurve','PhCrop','PhEraser','PhIntersect','PhMagicWand','PhMagnet','PhPerspective','PhRuler','PhScissors','PhScribbleLoop','PhStamp','PhCube','PhCylinder','Ph2stackSimple','PhStack','PhGridFour','PhLayout','PhSidebar','PhSidebarSimple','PhCirclesFour','PhCirclesThree','PhDiamondsFour','PhSquaresFour',

    '__wellness__',
    'PhBarbell','PhHeartBreak','PhHeartbeat','PhSparkle','PhActivity','PhBandaids','PhBrain','PhFaceMask','PhFirstAid','PhFirstAidKit','PhLifebuoy','PhPill','PhPrescription','PhSkull','PhSyringe','PhAtom','PhFlask','PhTestTube',

    '__nature-weather__',
    'PhCampfire','PhDrop','PhFire','PhFlame','PhLightning','PhWaves','PhWind','PhBird','PhBug','PhButterfly','PhCat','PhDog','PhFish','PhHorse','PhPawPrint','PhCactus','PhFlower','PhFlowerLotus','PhLeaf','PhMountains','PhTreeEvergreen','PhTree','PhGlobeHemisphereEast','PhGlobeHemisphereWest','PhMoon','PhPlanet','PhCloud','PhRainbow','PhSnowflake','PhSunDim','PhSun','PhUmbrellaSimple','PhUmbrella','PhThermometerSimple','PhThermometerCold','PhThermometerHot',

    '__people__',
    'PhUser','PhUsers','PhUsers3three','PhUsersFour','Ph1personSimple','PhPerson','PhWheelchair','PhBaby','PhEar','PhEyeClosed','PhEye','PhHandFist','PhHandGrabbing','PhHandPalm','PhHandPointing','PhHandWaving','PhHand','PhHandsClapping','PhHandshake','PhSmiley','PhSmileyBlank','PhSmileyMeh','PhSmileyNervous','PhSmileySad','PhSmileySticker','PhSmileyWink','PhSmileyXEyes','PhGenderFemale','PhGenderIntersex','PhGenderMale','PhGenderNeuter','PhGenderNonbinary','PhGenderTransgender','PhHandEye','PhPeace','PhYinYang',

    '__logo__',
    'PhFacebookLogo','PhInstagramLogo','PhPinterestLogo','PhTiktokLogo','PhTwitchLogo','PhTwitterLogo','PhYoutubeLogo','PhLinkedinLogo','PhRedditLogo','PhSnapchatLogo','PhBehanceLogo','PhDribbbleLogo','PhMediumLogo','PhNyTimesLogo','PhRssSimple','PhRss','PhFigmaLogo','PhFramerLogo','PhSketchLogo','PhCodepenLogo','PhGithubLogo','PhDiscordLogo','PhSlackLogo','PhAppStoreLogo','PhGooglePlayLogo','PhApplePodcastsLogo','PhGooglePodcastsLogo','PhSpotifyLogo',

    '__tools__',
    'PhLinkSimpleHorizontalBreak','PhLinkSimpleHorizontal','PhLinkBreak','PhLinkSimple','PhLink','PhPaperclipHorizontal','PhPaperclip','PhTextBolder','PhTextH','PhTextItalic','PhTextStrikethrough','PhTextT','PhTextUnderline','PhFunction','PhTextAa','PhTextIndent','PhTextOutdent','PhTextAlignCenter','PhTextAlignJustify','PhTextAlignLeft','PhTextAlignRight','PhListBullets','PhListNumbers','PhFunnelSimple','PhSortAscending','PhSortDescending','PhBackspace','PhKeyReturn','PhArrowElbowDownLeft','PhCommand','PhOption','PhColumns','PhRows','PhAlignBottomSimple','PhAlignCenterHorizontalSimple','PhAlignCenterVerticalSimple','PhAlignLeftSimple','PhAlignRightSimple','PhAlignTopSimple','PhAlignBottom','PhAlignCenterHorizontal','PhAlignCenterVertical','PhAlignLeft','PhAlignRight','PhAlignTop','PhGradient','PhCircleHalf','PhCircleHalfTilt','PhDropHalfBottom','PhDropHalf','PhSquareHalfBottom','PhSquareHalf','PhLineSegment','PhLineSegments','PhPolygon','PhBoundingBox','PhSelection','PhGitBranch','PhGitCommit','PhGitDiff','PhGitFork','PhGitMerge','PhGitPullRequest','PhArrowBendUpLeft','PhArrowBendUpRight','PhArrowUUpLeft','PhArrowUUpRight','PhArrowClockwise','PhArrowCounterClockwise','PhArrowsClockwise','PhArrowsCounterClockwise','PhArrowsHorizontal','PhArrowsVertical','PhArrowsDownUp','PhArrowsLeftRight','PhArrowLineDown','PhArrowLineLeft','PhArrowLineRight','PhArrowLineUp','PhArrowsInLineHorizontal','PhArrowsInLineVertical','PhArrowsOutLineHorizontal','PhArrowsOutLineVertical','PhArrowsInSimple','PhArrowsOutSimple','PhPause','PhPlay','PhRecord','PhStop','PhRepeatOnce','PhRepeat','PhShuffle','PhFastForward','PhRewind','PhSkipBack','PhSkipForward','PhSpeakerHigh','PhSpeakerLow','PhSpeakerNone','PhSpeakerSlash','PhSpeakerX','PhClosedCaptioning','PhCornersIn','PhCornersOut','PhFrameCorners','PhPictureInPicture','PhAirplay','PhScreencast','PhEject','PhPower','PhDotsThreeVertical','PhDotsThree']};